### ISSUE TITLE
Issues to potentially discuss at design meeting

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/build-a-nucleus#11]
1. It’s unconventional to show ex. 3.9 x10^0 s, should we consider switching out of scientific notation when we get to  a situation like this, or just stay consisten

2. Electron cloud - should we scale to atomic radius

3. Should the nucleus recoil with alpha decay?

4. Shaking nucleus if unstable? 

5. Electron cloud - is this the best way to "orient" users to the idea that we are in the nucleus

**Comment by ariel-phet** [comment]
Design meeting 2022-04-28

KP: Having some constraint on what arrows you can use in certain situations (disabling a removal arrow) seems reasonable. 

KP/AR: Like the icons for decays for clarification

Shaking nucleus: AR and KP do not necessarily feel shaking is necessary. If we did implement this feature probably best to have an option that is off by default.

Electron cloud: KP likes having the orientation of the electron cloud. AR we do want to scale the size of the electron cloud. Change wording to "Electron Cloud" and use and icon. 

AR: Consider high contrast mode (let's make an issue for this)

Recoil: AR/KP do not model recoil for decays (make clear in teacher tips we are using the nuclear frame of reference)

Scientific notation: AR/KP likes showing "2.5 s" vs 2.5x10^0 s

**Comment by ariel-phet** [comment]
As of 2022-05-11

1. When there is just a single neutron (or 2 or 4 isolated ones), what should the "Symbol" node read, a blank or a dash? (currently in BAA this display is inconsistent, it shows a dash for the periodic table display and a blank for the symbol readout)

**Comment by Luisav1** [comment]
Design meeting 2022-05-19

Beta decay symbol design (AR, KP, KW): shorten all decay button lengths overall. Make the arrows shorter and in a new level below have "+ {motion lines} electron/positron"

Beta decay nucleon change animation (KW): slow down the change from one color to the other.

KP uniform sizing for electrons/positrons all over - smaller when emitted from the nucleus and smaller in the legend because it is smaller in the beta decay symbols.

Fade in/fade out (flashing) nucleon counter: AR/KP like it but KP feels that she just watches nucleons going in and out not really the counter. KW but with the arrow moving around a lot, eyes gravitate towards there.

Info dialog centering: CK/AR add padding to edges so always in center. KP left align the text when stable with the arrow and shorten the arrow like in the main timescale. KP maybe try JO's new scenery layout.

KP the dash for the symbol node when there are no protons is good.

Prototype timeline goals: Goal to finish pixel polishing in the next week and then QA after. KP/AP good for CM to code review for LV's learning experience. CK will also code review but outside perspective (CM) is good. KP - LV also do self code review.

**Comment by Luisav1** [comment]
All of these changes were done. Closing.
