### ISSUE TITLE
Stable string doesn't show on dev version

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#116]
During interviews using the current latest [dev version](https://phet-dev.colorado.edu/html/build-a-nucleus/1.0.0-dev.20/phet/build-a-nucleus_all_phet.html), we saw that the stable string doesn't show up unless the page is refreshed.
![image](https://github.com/phetsims/build-a-nucleus/assets/52978048/8280ca98-7ac2-4011-8471-7792d9d4c4c5)

**Comment by zepumph** [comment]
This isn't immediately reproducible by @Luisav1 and I, and we are a bit stumped. @arouinfar can you report the device that the interviewee was using and if there want any other pertinent info that would be important to share? Otherwise we will have QA hammer on it with some devices to try to reproduce (which I'd rather not waste their time on if we don't have to).

**Comment by Luisav1** [comment]
@zepumph and I investigated the creation of these legend items and didn't see any issues there. Leaving this so QA can test on this.

**Comment by zepumph** [comment]
QA feel free to close

**Comment by Nancy-Salpepi** [comment]
I was unable to reproduce with mac + safari/chrome and Win10 + chrome. 
Leaving open until @KatieWoe takes a look.

**Comment by KatieWoe** [comment]
I didn't see this either
