### ISSUE TITLE
Move addNucleonImmediatelyToAtom and populateAtom from BANScreenView to BANModel

### ISSUE THREAD

**Issue by Luisav1** [phetsims/build-a-nucleus#136]
From #112. These functions contain only model components and should be in BANModel instead of BANScreenView.

**Comment by zepumph** [comment]
While I was here, I also made `moveAllToDestination`. @Luisav1 now we don't have animations when we use the starting particle count query parameters for the chart screen. Can you please review. I feel a bit like I'm missing something. 

It is a bit weird because on the particleNucleus, the animations are all done from `reconfigureNucleus` so it seems much easier just cancel out the animation after adding h particles than to try to sprinkle through a parameter like `shouldAnimate` into addParticle -> reconfigureNucleus -> reconfigureNucleus override. Let me know if you don't like the above commits.

**Comment by Luisav1** [comment]
I like the above commits and I agree that it's much simpler / straightforward than still sticking with using reconfigureNucleus and passing in `shouldAnimate`. Thanks, closing.
