### ISSUE TITLE
Can we use `ParticleAtom.extractParticleClosestToCenter()` instead of `BANModel.getParticleToReturn`

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#188]
Promoting TOOD made while investigating https://github.com/phetsims/build-a-nucleus/issues/105.

This is a newish function, so it could replace this older code.

**Comment by Luisav1** [comment]
This can't be done because of two things:
- `getParticleToReturn` returns the particle closest to the particles creator node while `extractParticleClosestToCenter` gets the particle closest to the center of the atom
- `extractParticleClosestToCenter` also extracts the particle, it removes it from the particle atom which we don't want being done until after the particle is animated away from the particle atom.
Closing.
