### ISSUE TITLE
Po 221 built

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-nucleus#204]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/988.
It is possible to make Po 221 even though the graph indicates it shouldn't exist. It can either be decayed into or built outright.

**Visuals**
![notdone](https://github.com/phetsims/build-a-nucleus/assets/41024075/0721c341-6976-4941-b2c9-b9c167998a82)
![Po221](https://github.com/phetsims/build-a-nucleus/assets/41024075/557a6dfd-e4f5-4ea3-8110-b00b8ab54c43)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Nucleus‬:‪Build a Nucleus‬
URL: https://phet-dev.colorado.edu/html/build-a-nucleus/1.1.0-rc.1/phet/build-a-nucleus_all_phet.html?stringTest=double
Version: 1.1.0-rc.1 2023-09-26 23:04:02 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Language: en-US
Window: 1536x731
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by Luisav1** [comment]
Thanks @KatieWoe. The data from the chart is a bit outdated since it was last updated May 2015. But the data in the sim is from February 2022 and is in this spreadsheet: https://docs.google.com/spreadsheets/d/1kVfWNMYeXEo5dAzQUI5ZKyZwIlnLiQkd/edit#gid=1440307797.

I checked with the table there and it seems Po-221 should form. Sorry for the confusion!
![image](https://github.com/phetsims/build-a-nucleus/assets/52978048/dc65c289-71f4-4ce2-918b-48a243737ebb)

Hopefully this clears any other potential similar issues. Closing.

**Comment by Luisav1** [comment]
This is the spreadsheet we are using and want testing done with: https://docs.google.com/spreadsheets/d/1kVfWNMYeXEo5dAzQUI5ZKyZwIlnLiQkd/edit#gid=1440307797. But when we added the nuclides up to 94 protons (see #42), this spreadsheet wasn't updated. So we need to update the spreadsheet.

**Comment by Luisav1** [comment]
The spreadsheet is now updated with the AtomIdentifier values up to 94 protons and 146 neutrons.
