### ISSUE TITLE
Is the Most Likely Decay Mode for Be-6 correct?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/build-a-nucleus#208]
For https://github.com/phetsims/qa/issues/988

On the Intro Chart Screen, Be-6 is shown to decay by proton emission (100%), but on the Decay screen, it shows both alpha and proton. After discussing with @Luisav1 over slack, she discovered that according to this website, https://www-nds.iaea.org/relnsd/vcharthtml/VChartHTML.html, Be-6 should undergo alpha decay.

![image](https://github.com/phetsims/build-a-nucleus/assets/87318828/11627788-2ad5-4a92-a37b-51e0de46b291)

@Luisav1 will discuss w/Jason to see if a change is needed.

**Comment by Luisav1** [comment]
Talking with Jason, the real decay mode for Be-6 is it emits an alpha particle and 2 protons, all at the same time. However, since a 'decay' is generally thought of as the bigger particle remains and a smaller particle (electron, proton, neutron, etc.)  is emitted, in this case it would make more sense to still keep on representing Be-6 as a proton emission decay type.

Even though the 'hollywood' fix done in the decay screen would have been a possibility (where an alpha particle leaves first and then the 2 remaining protons are emitted), it's not as accurate.

Therefore, the Be-6 most likely decay for Be-6 remaining as a proton emission is alright and correct.

**Comment by Luisav1** [comment]
Since we're keeping at as a proton emission this doesn't need to be addressed. Closing.
