### ISSUE TITLE
Complete model.md and implementation-notes.md

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-a-nucleus#94]
@Luisav1, this is a good thing to do while we are still in the thick of development. In general, model.md is more of a public-facing doc to describe how we implemented the physics. This is a great chance to note some of the shortcommings (like the beta decay of uranium for example) and other "hollywooding" we may have done. In implementation-notes, make sure to add any qualities or patterns or oddities that may assist the next person in maintaining the sim.

Thanks!

**Comment by zepumph** [comment]
* Define important and nuanced terms like "Atom", "ParticleAtom", "Particle", "Nucleus" vs "Atom", and the difference (if there is one) between "View" and "Node".

**Comment by Luisav1** [comment]
- [x] model.md should say placement of particles is not scientifically accurate
- [ ] all the special cases and 'hollywooding' done
  - [x] ex. Beryllium - 4 and the case where 2 protons remain
  - [x] particles not true to size, just easier to visually represent them as circles (same note as in BAA and IAAM).
  - [x] review half-life cases
  - [x] review the 0,0 cases
  - [x] case where third level holds 12 particles but looks like it holds 6 so it fits.
- [x] update the MVT section since NUCLEON_ENERGY_LEVELS_MVT no longer exists and other MVT updates. See #182.
- [x] half-life's and decays data taken from hard-coded data from 2022. Include link to it.
  - [x] Note that info coming from experimental data

**Comment by Luisav1** [comment]
Added points on special cases and 'hollywooding' done in commits above, with other notes too both in model and implementation-notes. @ariel-phet could you review these to make sure they're okay or let me know if you have any suggestions? Thanks!

**Comment by ariel-phet** [comment]
@Luisav1, a few questions/comments:

For model.md
- [x] 1. Where you define "Decay" - I think a definition more relevant to the sim might be appropriate. Generally radiation is understood to be electromagnetic radiation. Here why probably want to say something like "the process by which an unstable atomic nucleus undergoes spontaneous transformation into a different nuclei. The decay process can involve the emission of subatomic particles, the transformation of particles, and the emission of radiation (photons). 

- [x] 2. We probably should mention that although decays can involve neutrinos (I believe both beta decays do) that aspect is beyond the scope of the sim

- [ ] 3. I am not sure I understand this statement under Decay screen: "If the electron cloud is visible, then an atom is being built, but if the electron cloud is not visible, then a nucleus is built." -- we don't really make this distinction clear in any aspect of the sim. Naming conventions and such are all the same. What was meant to be clarified by this statement?

I don't really have any comments on the implementation notes, as those tend to be a bit more developer focused, but reading through them, no issues stood out to me.

**Comment by Luisav1** [comment]
For 3. I added that statement since I was trying to in a way justify the reason for the checkbox though checking back in the [doc](https://docs.google.com/document/d/12kmOdYKG1DWgMHGodMsY-rO75QS3xxHrzrjkJpqPUxQ/edit), it seems we only added it to orient that we are in the nucleus or to match BAA.
![image](https://github.com/phetsims/build-a-nucleus/assets/52978048/722789b4-67cf-49a9-be32-064af61d94da)
@ariel-phet Do you think that statement is not that necessary such that this is clear or should I reword it?

**Comment by ariel-phet** [comment]
@Luisav1 I think I would just reword the statement, something like "The electron cloud is provided as an option to help orient users that the nucleus is being constructed within the context of an atom"

**Comment by Luisav1** [comment]
Reworded the electron cloud statement in the commit above and completed the model and implementation-notes after a review by @ariel-phet. Closing.
